sonar.organization=gszigethy
sonar.projectKey=gszigethy_444hu_comments

sonar.sources=.
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=.github/**,tests/**,images/**,dist/**,coverage/**,node_modules/**,backburner.js
sonar.cpd.exclusions=tests/**

sonar.python.version=3.13
